# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneMacos: "America/New_York"

    - uses: nanasess/setup-chromedriver@v1
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Run functional tests
      env:
        NODE_OPTIONS: "--max-old-space-size=8192"
      run: npm run functional:ci

    - name: Run Lint Checks
      env:
        NODE_OPTIONS: "--max-old-space-size=8192"
      run: npm run lint:ci

    - name: Run puppeteer tests
      env:
        NODE_OPTIONS: "--max-old-space-size=8192"
      run:  (npm run quickstart &) && sleep 5; npm run e2e:puppeteer;

    - name: Run e2e tests
      env:
        NODE_OPTIONS: "--max-old-space-size=8192"
      run:  (npm run quickstart &) && sleep 5; npm run e2e:ci:debug;

    - name: Deploy Main
      env:
        JENKINS_JOB_TOKEN: ${{ secrets.JENKINS_JOB_TOKEN }}
        JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
      if: github.event_name == 'push'
      run: sh ./scripts/jenkins-deploy.sh -b main

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
